### ISSUE TITLE
Store Version not compatible with Tango DevTablet

### ISSUE THREAD

**Issue by cefoot** [lvonasek/tango#1]
Store says: "device not compatible with version"

I would love to try this, but sadly mentioned message appears.

Is it the same with the source code? You have the tablet? 
Hey I support you? 

Regards from Germany 😊

**Comment by lvonasek** [comment]
Hi, I made some update in code to make it working on a tango devkit but I cannot guarantee anything as I do not have the tablet. Please try both of APKs and tell me which of them is working for you:

http://xar007.xf.cz/OpenConstructor-unofficial-libtango_device.apk
http://xar007.xf.cz/OpenConstructor-unofficial-libtango_device2.apk

Note: this APKs are made from last git so it is development version and not release version.

Regards from Czech guy living in Germany

**Comment by cefoot** [comment]
Hey, that was fast 😜 both install and seem to work just fine (did not test too much detail for now)

But I think I'll step in the code and do some changes to make it usable(for example display orientation should be landscape on table 🙌)

But it looks awesome!! Thx so much 
Please keep working on it😉 I'll definitely follow and try to be active

**Comment by lvonasek** [comment]
Cool, on the Lenovo Phab2 Pro is working second build only.
I am closing this issue - it will be working in the next release(probably next week).

The version I sent you is missing linking with external model viewer app. Next version will have build-in viewer.
