### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by adamjokull** [lvonasek/tango#10]
Hi, are you planning those function (like tango constructor have) in your app?
1. 3rd and plan view in capture mode (usefull to see what did you scan already)
2. orbit navigation mode in model view 
3. thumbnails 
4. when saving put some automatic name (like date and time)
5. save scan without postprocessing (usefull if i want to make few scans of site and dont have time and battery for postprocess)
6. make folder for each scan separetly in file structure

anyway thank you very much for your work, your app is really great!

**Comment by lvonasek** [comment]
Hi,

currently I am more concentrating on removing memory limits and improving quality, anyway I will add 1.,2. and 3. into my personal todolist. That means that I will implement it but currently I have no clue when I will find time on it.

4. is already in plan for the next version
5. is already in development - it will be possible to pause scanning, turn of phone and later postprocces model
6. I plan to do in future release (not sure when exactly) saving into ZIP - inside will be objs (subdivided by grid) and textures
