### ISSUE TITLE
Where is the 3D model stored in  the latest version？

### ISSUE THREAD

**Issue by qiangyonglong** [lvonasek/tango#13]
Hi，
 The Tango device I use is the TellowStone tablet，The last release version is 0.65. The obj model is saved under the models folder of the SD card. But I can not find it in  the latest version.

Best.

**Comment by lvonasek** [comment]
Hi, it is stored in Models folder of internal memory storage. It was never stored on SD card.

**Comment by qiangyonglong** [comment]
thanks，but I also not find the new model in Models folder of internal memory storage. The old obj models 
Only exist.

**Comment by lvonasek** [comment]
When you are accessing device data from computer it offen shows old (cached) data only (it is problem with MTP protocol). Check it using file manager on tablet.

**Comment by qiangyonglong** [comment]
thanks. I do see cached data.
