### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by tsukasa1989** [lvonasek/tango#15]
Hello,

I want to build the project but getting an error in the build-binary.mk on line 528:

`$(foreach src,$(filter %.c,$(LOCAL_SRC_FILES)), $(call compile-c-source,$(src),$(call get-object-name,$(src))))`

Message:
`*** multiple target pattersns. Stop.`

Any suggestions?

Thank you,

Niels

**Comment by lvonasek** [comment]
Hi, building is supported on Linux only. I am not sure why it does not build on Windows (probably some bug in Android NDK)

Lubos
