### ISSUE TITLE
Support for Pixel 2?

### ISSUE THREAD

**Issue by tnoel125** [lvonasek/tango#17]
Hi, 

Would this work on the Pixel 2? It's not supported in the google play store but I thought maybe the supported devices just hadn't been updated recently.  

Thanks!

**Comment by lvonasek** [comment]
Hi, Pixel 2 does not have depth sensor and ARcore does not support 3DR. So the answer is no.

**Comment by lvonasek** [comment]
OK, I changed my mind:
https://play.google.com/store/apps/details?id=com.lvonasek.arcore3dscanner

**Comment by tnoel125** [comment]
Thank you! I'll check it out.

Todd
