### ISSUE TITLE
keeps on processing the model....

### ISSUE THREAD

**Issue by GiorgosTzagk** [lvonasek/tango#18]
First o f all thank you for your try to give us a usefull app.I dont know what is wrong. After any scan i make (small ones) the app keeps on the processing screen. (The app is working, please do not....) for ever. I left the phab2pro all night on that screen to see if it just needs time but nothing changed. I would really love to be able to use your app.

**Comment by lvonasek** [comment]
Hi, this is a known bug of Tango Core. Sometimes some app brings it into inconsistent state and then some Tango apps does not work correctly. If this problem happens then you have to restart your phone to make it working again. Give it try. If you find out which app causes this then give me know

**Comment by lvonasek** [comment]
I finally fixed it, it is in the Google Play beta:
https://play.google.com/apps/testing/com.lvonasek.openconstructor
