### ISSUE TITLE
Question Regarding Tango function

### ISSUE THREAD

**Issue by waitaria** [lvonasek/tango#19]
Hi, I am working on a tango app of my own, and was intrigued by how you get the mapping of the colour image to the pointcloud. I was wondering if you could please explain to me how you do this? I am using the ASUS Zenfone AR, and my mapping is currently correct. The colour image is offset to the right and above the corresponding pointcloud.

Thanks a lot for your help!

**Comment by lvonasek** [comment]
Hi, currently I am using Tango3DR implementation (it adds color to vertices when I do ExtractMesh).
I had version where I computed it myself (at https://github.com/lvonasek/tango/tree/be8c2877e91cca16205b46e64306b803c11b62af/open_constructor/app/src/main/jni ):

    static inline void convert2uv(glm::vec4 &v, glm::mat4 &world2uv,
                                  Tango3DR_CameraCalibration &calibration) {
        v = world2uv * v;
        v.x /= glm::abs(v.w * v.z);
        v.y /= glm::abs(v.w * v.z);
        v.x *= calibration.fx / (float)calibration.width;
        v.y *= calibration.fy / (float)calibration.height;
        v.x += calibration.cx / (float)calibration.width;
        v.y += calibration.cy / (float)calibration.height;
    }

//v is coordinate in the world space (x, y, z, 1)
//world2uv is matrix to convert world space to uv of texture:
        TangoMatrixTransformData matrix_transform;
        TangoSupport_getMatrixTransformAtTime(
                        buffer->timestamp, TANGO_COORDINATE_FRAME_AREA_DESCRIPTION,
                        TANGO_COORDINATE_FRAME_CAMERA_COLOR, TANGO_SUPPORT_ENGINE_OPENGL,
                        TANGO_SUPPORT_ENGINE_TANGO, ROTATION_0, &matrix_transform);
        if (matrix_transform.status_code != TANGO_POSE_VALID)
            return;
        image_matrix = glm::make_mat4(matrix_transform.matrix);
        world2uv = glm::inverse(image_matrix);

//calibration is camera calibration provided by Tango:
        TangoCameraIntrinsics intrinsics;
        err = TangoService_getCameraIntrinsics(TANGO_CAMERA_COLOR, &intrinsics);
        if (err != TANGO_SUCCESS)
            std::exit(EXIT_SUCCESS);
        calibration.calibration_type =
                static_cast<Tango3DR_TangoCalibrationType>(intrinsics.calibration_type);
        calibration.width = intrinsics.width;
        calibration.height = intrinsics.height;
        calibration.fx = intrinsics.fx;
        calibration.fy = intrinsics.fy;
        calibration.cx = intrinsics.cx;
        calibration.cy = intrinsics.cy;
        std::copy(std::begin(intrinsics.distortion), std::end(intrinsics.distortion),
                  std::begin(calibration.distortion));

coordinates of pixel in texture are written in v. I am not sure if it is in range <-1,1> or <0,1>. But in all cases you have to multiply it with texture resolution before reading it.

**Comment by waitaria** [comment]
Thanks a lot for your help! Does this mapping depend on whether the phone is held in portrait or landscape orientation?

**Comment by lvonasek** [comment]
Only if you set correct rotation when calling TangoSupport_getMatrixTransformAtTime

ROTATION_0 is portrait I think
