### ISSUE TITLE
Turning auto exposure and iso to manual mode

### ISSUE THREAD

**Issue by miguelriemoliveira** [lvonasek/tango#20]
Hello,

I was wondering how it could be possible to turn off auto exposure and auto brightness. 

There are some links which show how this can be done using tango

http://www.vioja.com/the-automatic-exposure-of-the-color-camera-does-not-work-in-java/
https://stackoverflow.com/questions/29759199/google-project-tango-taking-pictures-while-tracking-motion
https://stackoverflow.com/questions/29759199/google-project-tango-taking-pictures-while-tracking-motion/30093618

The reason I am asking is because when creating a model in a scene which is not uniformly lit, the created textures have artifacts. For example, when we turn the tango device towards a window the auto-brightness function will detect that the image is brighter and adjust the auto-brightness accordingly. The result is that when we merge images before and after this adjustment the texture displays ugly artifacts.

See for example the wall in the image bellow, the wall seems to have two colors:

![bad](https://user-images.githubusercontent.com/11350998/36422079-ba5f4fe6-1632-11e8-8308-c732f4bc27a3.png)

I believe that disabling auto-brightness could improve this. Is there any other way you could think of to solve this?

Thanks in advance.

PS: congratulations on the great work!

**Comment by lvonasek** [comment]
Hi, the camera control was removed from Tango in 2016 (it was never working on Lenovo Phab2Pro or Asus ZenfoneAR). The links are pointing on solution which does not work anymore).

There is some color calibration in texturing process but it does not work well when the scan is not closed (as it is using radiosity). This is a bug of Google Tango, you can report it to Tango's github but it wont help as Google stopped supporting Tango from the August 2017.

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek ,

thanks for the repply. I agree with you that contacting google will not work. One other possibility would be to color correct the images used for creating the textures using some offline procedure. But for that I would need to access the images, color correct them and then use them to texture map.

Is it possible for the application to save in the models folder also the images used for texturing (along with information about the camera pose)? Google constructor developer does this for example.

Thanks in advance.

Miguel

**Comment by lvonasek** [comment]
In the moment when you finish scanning the images, poses and untextured model are stored in Models/dataset. The poses are in text files. For one position there are 3 poses (camera, depth, device), if you do not resume scanning then only camera pose will be used. When you press finish in the app, it applies the textures from the dataset and later it deletes the dataset.

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek 

Thanks for the repply. I saved a dataset. Concerning the txt file for each camera. Can you tell me if my assumptions are correct?

```
3
0.768300 -0.006883 -0.640053 0.000000
0.020602 -0.999158 0.035474 0.000000
-0.639758 -0.040441 -0.767511 0.000000
-0.293721 0.007573 0.122499 1.000000
-0.763887 0.005422 0.645327 0.000000
-0.025907 0.998901 -0.039059 0.000000
-0.644830 -0.046555 -0.762907 0.000000
-0.283288 0.007842 0.118334 1.000000
-0.029717 0.998833 -0.038075 0.000000
-0.760676 0.002113 0.649128 0.000000
0.648451 0.048252 0.759725 0.000000
-0.254234 0.000720 0.096176 1.000000
248.445531
```

first line I do not know.


```
0.768300 -0.006883 -0.640053 0.000000
0.020602 -0.999158 0.035474 0.000000
-0.639758 -0.040441 -0.767511 0.000000
-0.293721 0.007573 0.122499 1.000000
```

lines 2 through 5

roto translation matrix in opengl format (column major), that is "-0.293721 0.007573 0.122499" should be the translations.

This transformation is given from the camera's pose to the world frame correct?

**Comment by lvonasek** [comment]
the first line is amount of matrices stored in file
lines 2 through 5 is pose of camera sensor
lines 6 through 9 is pose of depth sensor
lines 10 through 13 is pose of device
the last line is timestamp

for texturing is used the pose of camera sensor and yes the coordinates, you sent me, are translations.

Note that pose do not contain camera calibration so if you use matrix inverse to read image coordinates then you get quite big error. I discussed it here:
https://github.com/lvonasek/tango/issues/19

Note that I do not extract the camera calibration into dataset.

**Comment by miguelriemoliveira** [comment]
Thank you @lvonasek 

I will use the intrinsics which are retrieved from the tango e.g.

```
camera_id: TANGO_3DR_CAMERA_COLOR
camera_intrinsics:
  calibration_type: TANGO_3DR_CALIBRATION_POLYNOMIAL_2_PARAMETERS
  width: 960
  height: 540
  model: [866.421028954913, 866.665121492082, 474.53935926186, 263.887274892649]
  distortion: [0.122687486206855, -0.560189137398671]
camera_extrinsics:
  orientation: [-0.00264532747463874, -0.99997185068565, 0.00393561721897875, 0.00581472234704451]
  translation: [0.0471387850768341, -0.00701568929038864, -0.00527641706946324]
```

**One more question** (I am sorry for all these questions): I have a color correction algorithm I would like to apply to the images. I designed this algorithm for RGBD cameras, i.e., it uses as input a list of rgb images (as usual) but also the disparity images (or range maps) provided by the 3D sensor.

The idea is to use the distance information to assess if there was an error in the pose estimation and, if so, not use that image (or portion of the image) for mapping the texture.

Thus my question: is it possible to save in the dataset also the range images associated with each rgb image?

Thank you so much for all your help.

Miguel

**Comment by lvonasek** [comment]
Depth sensor data are not synchronised with camera data so there would be needed to do some convertations and then storing it into image but it would be very noisy. Tango sensor is not so good.

You would get better results if you generate depthmap from obj model.

You can use my glut_viewer in this repository (it is a linux program openable with QTcreator to view OBJs), change shader to render depth, change it to use pose from file and then get the depth data as array using glReadPixels.

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek 

Thanks for the reply. I will try out your glut_viewer suggestion.

The reason I wanted the measured 3D data and don't wont to generate it from the mesh model is that **my validation is done exactly by assessing if the depth generated from the model and the one measured by the sensor are consistent.** This consistency check does not require a lot of precision, which is why the depth sensor inaccuracy should not be a problem.  I have tried this algorithm with data from an asus xtion which has the same Primesense Carmine chip so the 3D data should be similar.

Thanks,

Miguel

**Comment by lvonasek** [comment]
If I find some free time, I will create a APK which will save into dataset also depth sensor data (but it will be transformed into 3D)

**Comment by miguelriemoliveira** [comment]
Thank you so much for that.

If it is a point cloud (in pcd or ply) there is no problem. I can convert back to range image if that's the case, provided that I know the pose of the camera (which I do from the txt files).

**Comment by lvonasek** [comment]
OK, it was easier than expected:
https://github.com/lvonasek/tango/commit/ad54fb80ffa2010168a1c1b2e8a86af4040c4a13

here is the APK:
https://github.com/lvonasek/tango-binary/blob/master/OpenConstructor/090.apk?raw=true

I am not sure whats wrong with Google's coordinate system. the 3DR mesh has swapped y,z axis (but after exporting into OBJ it is OK) and when I convert point cloud it has z in incorrect direction. Anyway I tested it the exported data in Blender and with default settings OBJ matches the PLY files (so I hope it is correct).

Note that I am quite interested in your research. Please keep me updated.

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek 

Thank you so much. I will work on it but I am not sure if I will have time this week (I have to prepare some classes for next Monday). Anyway, next week I should give you some news. Also, I will try to recover some results I had using the asus camera and share with you.

Thanks once again. 

Miguel

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek 

I gave it a try and I now have ply's. Thanks. 

I was going to start applying my method and found out I cannot use these ply files because the vertices cannot be associated to the pixels in the image. See bellow a detailed explanation (1).

From what I've seen Tango does not provide a way to get the dense point cloud, but it does provide a way to generate an approximation from the sparse point cloud, see [here](https://developers.google.com/tango/apis/c/support/reference/group/depth-interpolation-support#group___depth_interpolation_support_1ga03a4e39d813814d837c24216f3ee105d)

This generates a [TangoSupportDepthBuffer](https://developers.google.com/tango/apis/c/support/reference/struct/tango-support-depth-buffer#struct_tango_support_depth_buffer) which I think [could be easily saved to a depth image](https://www.google.pt/search?q=kinect+depth+image&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwicgILRo7zZAhUBmVkKHYOPAB8QsAQILQ&biw=1536&bih=750)

Do you think this could be done? Can you give me some tips? I could try to give it a shot next week (or the one after that) but I've never used the google tango api ...

There is another path which is to do raycasting from each pixel to the point cloud but I think this way is more complicated, see:

1. https://stackoverflow.com/questions/47376518/how-to-construct-depth-image-using-the-point-cloud-data-from-tango
2. https://stackoverflow.com/questions/41572682/tango-raw-depth-data-update?rq=1
3. https://stackoverflow.com/questions/41593575/accessing-depth-camera-via-android-sdk?rq=1


(1) The problem is that these are not dense point clouds, rather they are sparse. That means that every pixel which did not get a valid 3D measurement should have a vertex with nan values. Because it does not, then I cannot say pixel index xxx corresponds to vertex index xxx. This is often called dense point cloud or organized point cloud in [pcl](http://pointclouds.org/documentation/tutorials/basic_structures.php) or [ros](http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html).

**Comment by lvonasek** [comment]
The thing is that point cloud data has information of "correctness" in the range <0,1>, this information is not stored in PLY. I am not sure how would exporting into image help you but I implemented it:
https://github.com/lvonasek/tango/commit/a2c704e295d3450db8b843d819e32434d9f73db7

It is the TangoSDK method so it should be the same like from Google's Constructor - 16bit pnm file
(Note that you have to use the second matrix in txt file if you transform it into 3D).

The updated APK is here:
https://github.com/lvonasek/tango-binary/blob/master/OpenConstructor/090.apk?raw=true
(make sure that you downloaded updated APK and not cached by browser, it is the same link... the diff between APK is exactly 300bytes).

Have a nice weekend

**Comment by miguelriemoliveira** [comment]
Hi Lubos (sorry my keyboard does not have your charachters),

Thanks for all your help. I will try it out asap and get back to you.

Have a nice weekend,

Miguel

**Comment by lvonasek** [comment]
Hi Miguel,

did you do some progress?

Luboš

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek ,

I did not say anything else because unfortunately I did not have any more time to work on this. 

I am teaching in a modular structure, which means I have all classes compacted into a month and a half ... I will still be teaching over 20 hours / week for the next month so I am afraid I can only promise results after this.

Anyway, if I find some time to advance before that I will let you know.

Best regards,

Miguel

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek ,

just to let you know that I will go back to work on this. Sorry, the period teaching classes took longer than expected. Let's see if I can get some results soon.

Regards,

Miguel

**Comment by lvonasek** [comment]
Hi,

I am glad. I made night vision for Tango (rendering depth map data from depth sensor): https://github.com/lvonasek/tango-binary/tree/master/NightVision
Maybe it will help you.

Regards,

Lubos

**Comment by miguelriemoliveira** [comment]
Hi, 

thanks. I will take a look at it and get back to you when I have news.

Regards,

Miguel
