### ISSUE TITLE
3D Scanner for ARcore; Crash on Xperia 

### ISSUE THREAD

**Issue by ARdisk** [lvonasek/tango#26]
Firstly, Thanks for developing this app, you got something really nice going here.

I´m having issues with "3D Scanner for ArCore" crashing in the middle of a scan. Sometimes it happens just a couple of seconds after i begin the scan. Or if im lucky(unlucky) i can scan for a full minute or so just to have it crash and loose the data before pressing save. I highly suspect it has something to do with the app struggling to find enough details in the image(like a white wall). But i´m not sure if this is always the case.

If you think this might be a issue with 3d scanner, and not ARCore itself. I will gladly help you hunting down the cause of crashing. Just show me the way.

**Phone:** Xperia xz1
**ArCore version:** 1.3.180604066
**3D Scanner for ar core version:** 2018-07-02

And a question unrelated to the crash.
The Xperia XZ1, like the Zenfone AR has a built in Tof sensor, but it lacks the support of TangoCore.
Do you think its possible to access depth data from xz1 Tof sensor to make it have better precision like with Open Constructor for Tango?

**Comment by lvonasek** [comment]
Hi, is it really crashing or just freezing?

If crashing then follow please the instructions here:
https://youtu.be/4EGdZI5z3W0

if freezing then it is known issue - ARcore lists motion tracking and it takes very long walking around the scanned area to recover the motion tracking.

---

About depth sensor:
I thought Xperia has ToF for face scanning (like iPhone X), also it is not possible to use it like on Asus Zenfone AR. Anyway ARcore is probably going to add depth sensor support soon (in ARcore 1.3 there is already a lot of code to support depth sensor but in the SDK there is still nothing about it). I will add the depth sensor support into 3D scanner for ARcore as soon as ARcore supports it.

**Comment by ARdisk** [comment]
Hi again,
It crashed (and rebooted for the most part). But now that i finally took the time to download android studio and set everything up... It just refuses to happen again. Now i only have the "freezing" you mentioned while the app waits for me to go back to the starting area.


Regarding the Depth sensor:
It is located on the back of the camera, and mainly used for setting the focus point. do you think this is less sophisticate Tof sensor, or do they all "see" the same thing?
The apps I’ve seen use the sensor beside the camera app, is Sonys own "3d creator" app and some built-in test app that displays the distance to whatever you point it at.

**Comment by lvonasek** [comment]
The ARcore was updated in between, maybe Google fixed it on own side.

Freezing I already fixed but I did not release it yet, maybe next week.

The ToF sensor are made of two parts:
1) lamp using infrared light (also people dont see it but some animals are quite annoyed by it) - this part is exactly the same for every ToF sensor (just the amount of light is different)
2) infrared light camera - here is the resolution of it very important, for measurement of distance you need at least one pixel (which can be case of your Sony but I do not know), Tango device has about 320x240 and it can be used like night vision: https://www.youtube.com/watch?v=ulujf1vcQBU (my app)

I decompile new ARcore 1.4 APK and it seems that it does not support the depth sensor yet. The list of the new supported devices is here in the comments:
https://plus.google.com/+ChuckKnowledge/posts/cXqQjijHA6b

**Comment by lvonasek** [comment]
This looks for me like an issue of ARcore, feel free to post it on ARcore's GitHub issue tracker.

**Comment by ARdisk** [comment]
Where is that exactly?
i have found https://github.com/google-ar/arcore-android-sdk but there is no mention of 1.4 and seems outdated :S

**Comment by ARdisk** [comment]
Ok, will make a post there later on.

about the Tof Sensor:
I´m actually not sure about the pixel count.  I have tried searching , but I cant find any documentation regarding Xperia specific APIs, including how to access “RGB C- IR” sensor data

if you happens to know anything about till fell free to tell me :)


(i have this doc about "MAX44005" sensor saved from earlier. 
but right now i cant find anything about THIS being the sensor used
[https://www.maximintegrated.com/en/products/sensors/MAX44005.html](https://www.maximintegrated.com/en/products/sensors/MAX44005.html))

**Comment by lvonasek** [comment]
As I understand the document you send me, it reads just one value (one
pixel).

ARdisk <notifications@github.com> schrieb am Mi., 1. Aug. 2018, 14:38:
