### ISSUE TITLE
[question] Aligning depth map with RGB image

### ISSUE THREAD

**Issue by pavan4** [lvonasek/tango#27]
Hello, 

Thanks for releasing this. I have been playing with your library with an ASUS phone.

I saw that you export a RGB image, point cloud (.ply), depth image (.pnm). 

The RGB image is typically 1920x1080 and the pnm file is of the resolution(172x224) 

How can I convert the pnm file or the ply file to get a png depth map matched in same resolution as the RGB image?

**Comment by lvonasek** [comment]
Hi, PNM is quite useless as it is Tango's internal stuff without any description.

In the repo is dataset viewer which is demonstrating how to handle dataset from the last beta version (in app.cc::loadPointcloud is a way how to calculate image coordinates for each point in PLY).

I can make a tool to create depthmap from dataset later this summer. Currently I am on a holiday. Creating FullHD depthmap in the real-time would cost too much performance.

**Comment by lvonasek** [comment]
I was bored few hours also I implemented the depthmap generating. I put the update on Google Play (version 0.9.8). The depthmaps are in PNG format and you get the distance in cm by R+G+B (in the range 0..765). Depthmaps are 10x smaller than captured photos but they are exactly aligned. The alpha channel is 0 when there is no matching depth infomation.

I close this issue, feel free to ask more questions here.

**Comment by pavan4** [comment]
thank you so much. I will try this out and let you know 👍
