### ISSUE TITLE
3D Preview stalls out

### ISSUE THREAD

**Issue by sobotka** [lvonasek/tango#28]
After a long scan, preview ceases to update regions. At first, repeated passing of the dot over areas may update after an extended period, and then eventually stalling out completely.

**Comment by lvonasek** [comment]
This is a bug of Tango3DR. In places where is too much noise is hard to create surface. I made a workaround solution for it. If you use poisson reconstruction then all holes are closed.

I guess that Google will reintroduce the 3D reconstruction library next year.

**Comment by sobotka** [comment]
I am not sure. It closes holes fine, it is after an extended period of sampling that it simply stops.

**Comment by lvonasek** [comment]
It is mostly problem when motion tracking drifts. Then it generates a lot of incorrect data which are later erased but the data structure keeps there broken. Sometimes it helps to watch the problematic area from many angles.

You can also avoid the issue by having stable motion tracking. When I want to do better quality models then I start scanning, walk around little bit. Then I delete the scan (it keeps motion tracking learned area) and scan the area.

It is not a problem of the app - the app just provides fronted to the Tango3DR backend. Pity that the backend is not supported by Google anymore...
