### ISSUE TITLE
Unable to compile on windows

### ISSUE THREAD

**Issue by arvindixonos** [lvonasek/tango#29]
I am trying to deploy openconstructor from my windows PC to my tango phone. I am not able to successfully compile the .mk files. Please help!

Error while executing process C:\AndroidSDK\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\tango-master\open_constructor\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\tango-master\open_constructor\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-23 NDK_OUT=C:/tango-master/open_constructor/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\tango-master\open_constructor\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

process_begin: CreateProcess(NULL, "", ...) failed.

*** multiple target patterns.  Stop.

**Comment by arvindixonos** [comment]
If i remove 

$(call import-module,libjpeg-turbo)

the error disappears but crashes on the device.

**Comment by lvonasek** [comment]
Hi,

I tried it on WIndows and I got totally different error... you can try to edit in third_party/libjpeg-turbo/Android.mk using correct line ending... e.g. replace:
LOCAL_SRC_FILES += \
        src/jsimd_none.c \
with
LOCAL_SRC_FILES += \
        src/jsimd_none.c

Give me know if it helped. Thank you
