### ISSUE TITLE
Texturing issue / image saving issue

### ISSUE THREAD

**Issue by mihaibujanca** [lvonasek/tango#3]
![Texturing looks wrong when viewing the model](https://cloud.githubusercontent.com/assets/3803777/23409153/7093f9e0-fdc2-11e6-8a28-5909bfdfee1d.png)
The saved images have a pink layer over them, usually affecting large portions of the image.

**Comment by lvonasek** [comment]
Thank you for the report.

Problem was in OBJ loader(texture indexing was broken), I fixed it in git, it will be in version 0.3.6 (hopefully this week)

**Comment by mihaibujanca** [comment]
Can confirm it works
