### ISSUE TITLE
deconstructor

### ISSUE THREAD

**Issue by x24870** [lvonasek/tango#6]
Hi, I read this project recently and I learned a lot , thanks!

My question is:
In mesh_builder_app.cc at line 171
You used "new" to allocate a "textureProcessor" class, but I can't find where you use "delete" to release it.
Will it not lead to memory leak? or my concept was wrong?

**Comment by lvonasek** [comment]
Hi,

this is quite complicated, textures are stored on GPU and it can be deleted from GLthread only (from MeshBuilderApp::OnDrawFrame). Other threads does not have access on GPU. Memory leak is there and I am aware of it. Anyway when you close scanning/viewing there is called std::exit and operating system removes it.

Currently I am rewriting whole rendering/scanning concept. I am closing this issue but if you want to talk about it more, we can discuss about it.

**Comment by x24870** [comment]
Got it.
Thanks for your explanation.


2017年4月16日 下午6:49，"Luboš Vonásek" <notifications@github.com>寫道：
